<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Dependencies" duration-ms="23" started-at="2021-10-03T10:12:36Z" finished-at="2021-10-03T10:12:36Z">
    <groups>
    </groups>
    <test name="test" duration-ms="23" started-at="2021-10-03T10:12:36Z" finished-at="2021-10-03T10:12:36Z">
      <class name="com.harry.demotestng.core.DependenciesTest">
        <test-method status="FAIL" signature="startCar()[pri:0, instance:com.harry.demotestng.core.DependenciesTest@2471cca7]" name="startCar" duration-ms="4" started-at="2021-10-03T10:12:36Z" finished-at="2021-10-03T10:12:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.harry.demotestng.core.DependenciesTest.startCar(DependenciesTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startCar -->
        <test-method status="PASS" signature="stopCar()[pri:0, instance:com.harry.demotestng.core.DependenciesTest@2471cca7]" name="stopCar" duration-ms="0" started-at="2021-10-03T10:12:36Z" depends-on-methods="com.harry.demotestng.core.DependenciesTest.driveCar" finished-at="2021-10-03T10:12:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopCar -->
        <test-method status="PASS" signature="parkCar()[pri:0, instance:com.harry.demotestng.core.DependenciesTest@2471cca7]" name="parkCar" duration-ms="1" started-at="2021-10-03T10:12:36Z" depends-on-methods="com.harry.demotestng.core.DependenciesTest.stopCar" finished-at="2021-10-03T10:12:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parkCar -->
        <test-method status="SKIP" signature="driveCar()[pri:0, instance:com.harry.demotestng.core.DependenciesTest@2471cca7]" name="driveCar" duration-ms="0" started-at="2021-10-03T10:12:36Z" depends-on-methods="com.harry.demotestng.core.DependenciesTest.startCar" finished-at="2021-10-03T10:12:36Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependenciesTest.driveCar()[pri:0, instance:com.harry.demotestng.core.DependenciesTest@2471cca7] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependenciesTest.driveCar()[pri:0, instance:com.harry.demotestng.core.DependenciesTest@2471cca7] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driveCar -->
      </class> <!-- com.harry.demotestng.core.DependenciesTest -->
    </test> <!-- test -->
  </suite> <!-- Dependencies -->
</testng-results>
